### ISSUE TITLE
GSM Phone shown as CDMA

### ISSUE THREAD

**Issue by HEllRZA** [Asido/SystemMonitor#12]
Small bug: my iPhone5 (GSM) A1429 is shown as CDMA.

Unfortunately there are two different A1429: CDMA (US/Japan) and GSM (Europe/Australia/Asia)

From Apple:

GSM model A1428: UMTS/HSPA+/DC-HSDPA (850, 900, 1900, 2100 MHz); GSM/EDGE (850, 900, 1800, 1900 MHz); LTE (Bands 4 and 17)

CDMA model A1429: CDMA EV-DO Rev. A and Rev. B (800, 1900, 2100 MHz); UMTS/HSPA+/DC-HSDPA (850, 900, 1900, 2100 MHz); GSM/EDGE (850, 900, 1800, 1900 MHz); LTE (Bands 1, 3, 5, 13, 25)

GSM model A1429: UMTS/HSPA+/DC-HSDPA (850, 900, 1900, 2100 MHz); GSM/EDGE (850, 900, 1800, 1900 MHz); LTE (Bands 1, 3, 5)

**Comment by asido** [comment]
#7 describes my thoughts. Unfortunately I don't have the devices to test.
