### ISSUE TITLE
Wrong Device Type (Wrong Radio Technology)

### ISSUE THREAD

**Issue by HEllRZA** [Asido/SystemMonitor#7]
V1.0.5 shows a A1429 device as "Apple iPhone 5 (CDMA)", but it is a GSM model. In fact, A1429 can be both, CDMA it GSM.

**Comment by asido** [comment]
That information is identified by looking up the device identifier. According to [this table](http://www.everyi.com/by-identifier/ipod-iphone-ipad-specs-by-model-identifier.html) the GSM and CDMA models segmented by `iPhone5,1` and `iPhone5,2` identifiers. Perhaps your device is actually GSM.
