### ISSUE TITLE
Request cmds tweak 

### ISSUE THREAD

**Issue by jau88** [Asido/SystemMonitor#9]
Is it possible to embed a halt/kill commands for system processes and block traffic on individual connections? I have a jailbroken device and would like to implement this feature for your application natively, rather than hooking a tweak externally.

**Comment by asido** [comment]
Definitely doable on a jailbroken device, but I don't own one to try. Besides, process section was removed due to Apple not allowing to query process information any longer. Could be a feature specifically for jailbroken devices only.
